feat(docker): support opensuse's move from openssl 1.1.x to 3.0.x (#3430)
* feat(docker): support opensuse's move from openssl 1.1.x to 3.0.x

* ci: rename opensuse-tumbleweed-amd64-openssl-1.1.x to opensuse-tumbleweed-amd64-openssl-3.0.x

diff --git a/docker/opensuse-tumbleweed-amd64-openssl-3.0.x/Dockerfile b/docker/opensuse-tumbleweed-amd64-openssl-3.0.x/Dockerfile
--- a/docker/opensuse-tumbleweed-amd64-openssl-3.0.x/Dockerfile
+++ b/docker/opensuse-tumbleweed-amd64-openssl-3.0.x/Dockerfile
@@ -20,13 +20,12 @@ RUN curl -fsSLO --compressed "https://nodejs.org/dist/v${NODE_VERSION}/node-v${N
   && rm "node-v${NODE_VERSION}-linux-${ARCH}.tar.xz" \
   && npm i -g yarn
 
-# Only OpenSSL 1.1 is expected to be on this system
-RUN ldconfig -p | grep ssl | sed "s/.*=>\s*//"
-RUN if [ ! -e /lib64/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 not found in /lib64/libssl.so.1.1'; exit 1; fi
-RUN if [ -e /lib64/libssl.so.3 ]; then echo 'OpenSSL 3 must not be installed (found in /lib64/libssl.so.3)'; exit 1; fi
+# Only OpenSSL 3 is expected to be on this system
+RUN if [ ! -e /lib64/libssl.so.3 ]; then echo 'OpenSSL 3 not found in /lib64/libssl.so.3'; exit 1; fi
+RUN if [ -e /lib64/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 must not be installed (found in /lib64/libssl.so.1.1)'; exit 1; fi
 
 # expected target platform for Prisma, retrieved by `prisma -v`
-ARG EXPECTED_PRISMA_TARGET_PLATFORM="debian-openssl-1.1.x"
+ARG EXPECTED_PRISMA_TARGET_PLATFORM="debian-openssl-3.0.x"
 ARG PRISMA_CLIENT_ENGINE_TYPE
 ARG PRISMA_CLI_QUERY_ENGINE_TYPE
 ARG CI
