feat(docker): moved Debian latest (`node:lts-slim`) to OpenSSL 3.0.x (#3659)
* feat(docker): moved Debian latest (node:lts-slim) to OpenSSL 3.0.x

* chore: add explanation about missing openssl in README

diff --git a/docker/debian-latest-amd64-openssl-3.0.x/Dockerfile b/docker/debian-latest-amd64-openssl-3.0.x/Dockerfile
--- a/docker/debian-latest-amd64-openssl-3.0.x/Dockerfile
+++ b/docker/debian-latest-amd64-openssl-3.0.x/Dockerfile
@@ -1,26 +1,27 @@
 # syntax=docker/dockerfile:1
 
-FROM arm64v8/node:lts-slim
+FROM node:lts-slim
 
 WORKDIR /usr/src/app
 COPY --from=app . ./
 COPY --from=utils . ./
 
 # Update system dependencies
-RUN apt-get update -y
+RUN apt-get update -y && \
+  apt-get install -y openssl
 
 # expected target architecture, retrieved by `uname -m`
-ARG EXPECTED_UNAME_ARCH="aarch64"
+ARG EXPECTED_UNAME_ARCH="x86_64"
 ENV EXPECTED_UNAME_ARCH=$EXPECTED_UNAME_ARCH
 RUN ./uname.sh
 
-# Only OpenSSL 1.1 is expected to be on this system
+# Only OpenSSL 3 is expected to be on this system
 RUN ldconfig -p | grep ssl | sed "s/.*=>\s*//"
-RUN if [ ! -e /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1* ]; then echo "OpenSSL 1.1 not found in /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1*"; exit 1; fi
-RUN if [ -e /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3* ]; then echo "OpenSSL 3 must not be installed (found in /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3*)"; exit 1; fi
+RUN if [ ! -e /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3* ]; then echo "OpenSSL 3 not found in /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3*"; exit 1; fi
+RUN if [ -e /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1* ]; then echo "OpenSSL 1.1 must not be installed (found in /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1*)"; exit 1; fi
 
 # expected target platform for Prisma, retrieved by `prisma -v`
-ARG EXPECTED_PRISMA_TARGET_PLATFORM="linux-arm64-openssl-1.1.x"
+ARG EXPECTED_PRISMA_TARGET_PLATFORM="debian-openssl-3.0.x"
 ARG PRISMA_CLIENT_ENGINE_TYPE
 ARG PRISMA_CLI_QUERY_ENGINE_TYPE
 ARG CI
