feat: update expectations on alpine amd64

diff --git a/docker/alpine-3.17-amd64-openssl-1.1.x/Dockerfile b/docker/alpine-3.17-amd64-openssl-1.1.x/Dockerfile
--- a/docker/alpine-3.17-amd64-openssl-1.1.x/Dockerfile
+++ b/docker/alpine-3.17-amd64-openssl-1.1.x/Dockerfile
@@ -6,14 +6,14 @@ WORKDIR /usr/src/app
 COPY --from=app . ./
 COPY --from=utils . ./
 
-RUN apk update
+RUN apk update && apk add openssl1.1-compat
 
-# Only OpenSSL 3 is expected to be on this system
+# Both OpenSSL 1.1 and OpenSSL 3 must be present after installing openssl1.1-compat
+RUN if [ ! -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 not found in /lib/libssl.so.1.1'; exit 1; fi
 RUN if [ ! -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 not found in /lib/libssl.so.3'; exit 1; fi
-RUN if [ -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 must not be installed (found in /lib/libssl.so.1.1)'; exit 1; fi
 
 # expected target platform for Prisma, retrieved by `prisma -v`
-ARG EXPECTED_PRISMA_TARGET_PLATFORM="linux-musl-openssl-3.0.x"
+ARG EXPECTED_PRISMA_TARGET_PLATFORM="linux-musl"
 ARG PRISMA_CLIENT_ENGINE_TYPE
 ARG PRISMA_CLI_QUERY_ENGINE_TYPE
 ARG CI
