feat: add docker support for Alpine arm64 (#3418)
* feat: add docker support for Alpine arm64

* chore: fix remaining conflicts

* Remove unrelated file

diff --git a/docker/alpine-3.17-arm64-openssl-3.0.x-with-libc/Dockerfile b/docker/alpine-3.17-arm64-openssl-3.0.x-with-libc/Dockerfile
--- a/docker/alpine-3.17-arm64-openssl-3.0.x-with-libc/Dockerfile
+++ b/docker/alpine-3.17-arm64-openssl-3.0.x-with-libc/Dockerfile
@@ -1,6 +1,6 @@
 # syntax=docker/dockerfile:1
 
-FROM node:lts-alpine3.16
+FROM node:lts-alpine3.17
 
 WORKDIR /usr/src/app
 COPY --from=app . ./
@@ -10,12 +10,12 @@ COPY --from=utils . ./
 RUN apk update \
   && apk add libc6-compat
 
-# Only OpenSSL 1.1 is expected to be on this system
-RUN if [ -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 must not be installed (found in /lib/libssl.so.3)'; exit 1; fi
-RUN if [ ! -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 not found in /lib/libssl.so.1.1'; exit 1; fi
+# Only OpenSSL 3 is expected to be on this system
+RUN if [ ! -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 not found in /lib/libssl.so.3'; exit 1; fi
+RUN if [ -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 must not be installed (found in /lib/libssl.so.1.1)'; exit 1; fi
 
 # expected target platform for Prisma, retrieved by `prisma -v`
-ARG EXPECTED_PRISMA_TARGET_PLATFORM="linux-arm64-openssl-1.1.x"
+ARG EXPECTED_PRISMA_TARGET_PLATFORM="linux-musl-arm64-openssl-3.0.x"
 ARG PRISMA_CLIENT_ENGINE_TYPE
 ARG PRISMA_CLI_QUERY_ENGINE_TYPE
 ARG CI
@@ -30,10 +30,6 @@ ENV PRISMA_TELEMETRY_INFORMATION=$PRISMA_TELEMETRY_INFORMATION
 ENV EXPECTED_PRISMA_TARGET_PLATFORM=$EXPECTED_PRISMA_TARGET_PLATFORM
 
 RUN yarn install
-
-# This will fail with:
-# Error: Unable to require(`/usr/src/app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
-#   Error relocating /usr/src/app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node: __register_atfork: symbol not found
 RUN ./version.sh
 RUN npx prisma generate
 
