Add openssl1.1-compat to test matrix

diff --git a/docker/alpine-latest-openssl1.1-compat/Dockerfile b/docker/alpine-latest-openssl1.1-compat/Dockerfile
--- a/docker/alpine-latest-openssl1.1-compat/Dockerfile
+++ b/docker/alpine-latest-openssl1.1-compat/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-alpine3.16
+FROM node:lts-alpine
 
 COPY . /usr/src/app/
 WORKDIR /usr/src/app
@@ -15,9 +15,11 @@ ENV CI=$CI
 ENV DEBUG=$DEBUG
 ENV PRISMA_TELEMETRY_INFORMATION=$PRISMA_TELEMETRY_INFORMATION
 
-# Only OpenSSL 1.1 is expected to be on this system
+RUN apk update && apk add openssl1.1-compat
+
+# Both OpenSSL 1.1 and OpenSSL 3 must be present after installing openssl1.1-compat
 RUN if [ ! -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 not found in /lib/libssl.so.1.1'; exit 1; fi
-RUN if [ -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 must not be installed (found in /lib/libssl.so.3)'; exit 1; fi
+RUN if [ ! -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 not found in /lib/libssl.so.3'; exit 1; fi
 
 RUN yarn install
 RUN npx prisma generate
diff --git a/docker/alpine-latest/Dockerfile b/docker/alpine-latest/Dockerfile
--- a/docker/alpine-latest/Dockerfile
+++ b/docker/alpine-latest/Dockerfile
@@ -15,6 +15,10 @@ ENV CI=$CI
 ENV DEBUG=$DEBUG
 ENV PRISMA_TELEMETRY_INFORMATION=$PRISMA_TELEMETRY_INFORMATION
 
+# Only OpenSSL 3 is expected to be on this system
+RUN if [ ! -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 not found in /lib/libssl.so.3'; exit 1; fi
+RUN if [ -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 must not be installed (found in /lib/libssl.so.1.1)'; exit 1; fi
+
 RUN yarn install
 RUN npx prisma generate
 RUN npx prisma -v
