feat: add "uname -m" check to debian/ubuntu Dockerfiles

diff --git a/docker/ubuntu-latest-amd64-openssl-3.0.x/Dockerfile b/docker/ubuntu-latest-amd64-openssl-3.0.x/Dockerfile
--- a/docker/ubuntu-latest-amd64-openssl-3.0.x/Dockerfile
+++ b/docker/ubuntu-latest-amd64-openssl-3.0.x/Dockerfile
@@ -17,10 +17,15 @@ RUN curl -fsSLO --compressed "https://nodejs.org/dist/v${NODE_VERSION}/node-v${N
   && rm "node-v${NODE_VERSION}-linux-${ARCH}.tar.xz" \
   && npm i -g yarn
 
-# Both OpenSSL 1.1 and OpenSSL 3 are expected to be on this system
+# expected target architecture, retrieved by `uname -m`
+ARG EXPECTED_UNAME_ARCH="x86_64"
+ENV EXPECTED_UNAME_ARCH=$EXPECTED_UNAME_ARCH
+RUN ./uname.sh
+
+# Only OpenSSL 3 is expected to be on this system
 RUN ldconfig -p | grep ssl
-RUN if [ ! -e /lib/x86_64-linux-gnu/libssl.so.3* ]; then echo 'OpenSSL 3 not found in /lib/x86_64-linux-gnu/libssl.so.3*'; exit 1; fi
-RUN if [ -e /lib/x86_64-linux-gnu/libssl.so.1.1* ]; then echo 'OpenSSL 1.1 must not be installed (found in /lib/x86_64-linux-gnu/libssl.so.1.1*)'; exit 1; fi
+RUN if [ ! -e /lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3* ]; then echo "OpenSSL 3 not found in /lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3*"; exit 1; fi
+RUN if [ -e /lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1* ]; then echo "OpenSSL 1.1 must not be installed (found in /lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1*)"; exit 1; fi
 
 # expected target platform for Prisma, retrieved by `prisma -v`
 ARG EXPECTED_PRISMA_TARGET_PLATFORM="debian-openssl-3.0.x"
