Alpine OpenSSL ecosystem-tests (#3310)

diff --git a/docker/alpine-latest/Dockerfile b/docker/alpine-latest/Dockerfile
--- a/docker/alpine-latest/Dockerfile
+++ b/docker/alpine-latest/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-alpine
+FROM node:current-alpine
 
 COPY . /usr/src/app/
 WORKDIR /usr/src/app
@@ -14,6 +14,10 @@ ENV PRISMA_CLI_QUERY_ENGINE_TYPE=$PRISMA_CLI_QUERY_ENGINE_TYPE
 ENV CI=$CI
 ENV DEBUG=$DEBUG
 ENV PRISMA_TELEMETRY_INFORMATION=$PRISMA_TELEMETRY_INFORMATION
+
+# Only OpenSSL 3 is expected to be on this system
+RUN if [ ! -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 not found in /lib/libssl.so.3'; exit 1; fi
+RUN if [ -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 must not be installed (found in /lib/libssl.so.1.1)'; exit 1; fi
 
 RUN yarn install
 RUN npx prisma generate
