feat: add "uname -m" check to debian/ubuntu Dockerfiles

diff --git a/docker/debian-buster-amd64-openssl-1.1.x/Dockerfile b/docker/debian-buster-amd64-openssl-1.1.x/Dockerfile
--- a/docker/debian-buster-amd64-openssl-1.1.x/Dockerfile
+++ b/docker/debian-buster-amd64-openssl-1.1.x/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-bullseye-slim
+FROM node:lts-buster-slim
 
 WORKDIR /usr/src/app
 COPY --from=app . ./
@@ -7,10 +7,15 @@ COPY --from=utils . ./
 # Update system dependencies
 RUN apt-get update -y
 
+# expected target architecture, retrieved by `uname -m`
+ARG EXPECTED_UNAME_ARCH="x86_64"
+ENV EXPECTED_UNAME_ARCH=$EXPECTED_UNAME_ARCH
+RUN ./uname.sh
+
 # Only OpenSSL 1.1 is expected to be on this system
 RUN ldconfig -p | grep ssl
-RUN if [ ! -e /usr/lib/x86_64-linux-gnu/libssl.so.1.1* ]; then echo 'OpenSSL 1.1 not found in /usr/lib/x86_64-linux-gnu/libssl.so.1.1*'; exit 1; fi
-RUN if [ -e /usr/lib/x86_64-linux-gnu/libssl.so.3* ]; then echo 'OpenSSL 3 must not be installed (found in /usr/lib/x86_64-linux-gnu/libssl.so.3*)'; exit 1; fi
+RUN if [ ! -e /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1* ]; then echo "OpenSSL 1.1 not found in /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.1.1*"; exit 1; fi
+RUN if [ -e /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3* ]; then echo "OpenSSL 3 must not be installed (found in /usr/lib/${EXPECTED_UNAME_ARCH}-linux-gnu/libssl.so.3*)"; exit 1; fi
 
 # expected target platform for Prisma, retrieved by `prisma -v`
 ARG EXPECTED_PRISMA_TARGET_PLATFORM="debian-openssl-1.1.x"
