feat(docker): add e2e test for Prisma target platform

diff --git a/docker/alpine-3.16/Dockerfile b/docker/alpine-3.16/Dockerfile
--- a/docker/alpine-3.16/Dockerfile
+++ b/docker/alpine-3.16/Dockerfile
@@ -1,8 +1,15 @@
 FROM node:lts-alpine3.16
 
-COPY . /usr/src/app/
 WORKDIR /usr/src/app
+COPY --from=app . ./
+COPY --from=utils . ./
 
+# Only OpenSSL 1.1 is expected to be on this system
+RUN if [ ! -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 not found in /lib/libssl.so.1.1'; exit 1; fi
+RUN if [ -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 must not be installed (found in /lib/libssl.so.3)'; exit 1; fi
+
+# expected target platform for Prisma, retrieved by `prisma -v`
+ARG EXPECTED_PRISMA_TARGET_PLATFORM="linux-musl-openssl-1.1.x"
 ARG PRISMA_CLIENT_ENGINE_TYPE
 ARG PRISMA_CLI_QUERY_ENGINE_TYPE
 ARG CI
@@ -14,14 +21,11 @@ ENV PRISMA_CLI_QUERY_ENGINE_TYPE=$PRISMA_CLI_QUERY_ENGINE_TYPE
 ENV CI=$CI
 ENV DEBUG=$DEBUG
 ENV PRISMA_TELEMETRY_INFORMATION=$PRISMA_TELEMETRY_INFORMATION
-
-# Only OpenSSL 1.1 is expected to be on this system
-RUN if [ ! -e /lib/libssl.so.1.1 ]; then echo 'OpenSSL 1.1 not found in /lib/libssl.so.1.1'; exit 1; fi
-RUN if [ -e /lib/libssl.so.3 ]; then echo 'OpenSSL 3 must not be installed (found in /lib/libssl.so.3)'; exit 1; fi
+ENV EXPECTED_PRISMA_TARGET_PLATFORM=$EXPECTED_PRISMA_TARGET_PLATFORM
 
 RUN yarn install
+RUN ./version.sh
 RUN npx prisma generate
-RUN npx prisma -v
 
 CMD node server.js
 EXPOSE 3000
